version: "3"

services:
  app:
    container_name: react-app
    image: react-app
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=35729
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "3000:3000"
      - "35729:35729"

