version: "3"

services:
  app:
    hostname: localhost
    container_name: angular-app
    image: angular-app
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=dev
      - CHOKIDAR_USEPOLLING=true
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "4200:4200"
      - "49153:49153"

